### ISSUE TITLE
RSS Feed

### ISSUE THREAD

**Issue by Rucknar** [infinityworksltd/engineering#8]
RSS feeds are used by a lot of people who aggregate their data into useful tools. 
Having RSS would also enable us to have a slack integration that posts to the #infinityworks channel in slack.

**Comment by a-h** [comment]
There is one at http://engineering.infinityworks.com/feed.xml

**Comment by a-h** [comment]
Well, it's actually Atom, but close enough? Do we need a link to it from the site?

**Comment by Rucknar** [comment]
Well i'll be darned. Is there a link off the main page i'm missing? I guess we should try make it obvious if possible. I'll setup the Slack integration now.
